DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS ARTICULO;

CREATE TABLE `almacen`.`CATEGORIA` 
( `cat_id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT, `cat_nombre` VARCHAR(50) NOT NULL);

CREATE TABLE `almacen`.`ARTICULO` ( `art_id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT, `art_nombre` VARCHAR(50) NOT NULL , `art_categoria` INT NOT NULL , `art_cantidad` INT NOT NULL,CONSTRAINT FK_CATEGORIA FOREIGN KEY (ART_CATEGORIA) REFERENCES CATEGORIA(CAT_ID) ON DELETE NO ACTION
ON UPDATE NO ACTION);

INSERT INTO CATEGORIA (CAT_NOMBRE ) values('Electrónica');
INSERT INTO CATEGORIA (CAT_NOMBRE ) values('Alimentación');
INSERT INTO CATEGORIA (CAT_NOMBRE ) values('Ropa');
INSERT INTO ARTICULO (ART_NOMBRE,ART_CATEGORIA,ART_CANTIDAD ) values('MONITOR','1','8');